// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmlGf_7LCbJYzySnOp1iRAmuXn7Kit9LM',
    appId: '1:535260281367:web:d14e9a658556c731c4fa52',
    messagingSenderId: '535260281367',
    projectId: 'walqimg-3344f',
    authDomain: 'walqimg-3344f.firebaseapp.com',
    storageBucket: 'walqimg-3344f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-exQoA3dg2jQwgj8t7TaQdXhrsOycSFs',
    appId: '1:535260281367:android:e12d054072ea33f3c4fa52',
    messagingSenderId: '535260281367',
    projectId: 'walqimg-3344f',
    storageBucket: 'walqimg-3344f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQst9J5AuudDaY1bpFx7TJ3jCOKhkk0s',
    appId: '1:535260281367:ios:c5a59147d3b2ae06c4fa52',
    messagingSenderId: '535260281367',
    projectId: 'walqimg-3344f',
    storageBucket: 'walqimg-3344f.appspot.com',
    iosClientId: '535260281367-ojbdk18t10ugqmog9h6jae87uatdgmlb.apps.googleusercontent.com',
    iosBundleId: 'com.walqfoodindustries.walqimg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXQst9J5AuudDaY1bpFx7TJ3jCOKhkk0s',
    appId: '1:535260281367:ios:c5a59147d3b2ae06c4fa52',
    messagingSenderId: '535260281367',
    projectId: 'walqimg-3344f',
    storageBucket: 'walqimg-3344f.appspot.com',
    iosClientId: '535260281367-ojbdk18t10ugqmog9h6jae87uatdgmlb.apps.googleusercontent.com',
    iosBundleId: 'com.walqfoodindustries.walqimg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmlGf_7LCbJYzySnOp1iRAmuXn7Kit9LM',
    appId: '1:535260281367:web:1da85ee8b74879d7c4fa52',
    messagingSenderId: '535260281367',
    projectId: 'walqimg-3344f',
    authDomain: 'walqimg-3344f.firebaseapp.com',
    storageBucket: 'walqimg-3344f.appspot.com',
  );

}